coverage:
  status:
    project:
      default:
        target: auto
        threshold: 3%
    patch: off
comment:
  layout: "header, diff, changes"
ignore:
  - "src/Tgstation.Server.Host/Database/Migrations"
