# At the time of writing this, I'm the only maintainer and I want the proper branch protections in place
# So I'm setting up actions to auto-approve my work, since no one else does :(
# - Dominion <3
name: "Auto-Approve Dominion's PRs"

on:
  pull_request_target:
    branches:
    - dev
    - master

jobs:
  approve-pr-if-dominion-is-author:
    name: Approve PR if Dominion is Author
    if: github.event.pull_request.user.login == 'Cyberboss'
    runs-on: ubuntu-latest
    steps:
    - name: GitHub API Call
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.number}}/reviews \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        -d '{"event":"APPROVE"}' \
        --fail
